name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: dotnet nuget add source --username lipa44 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/lipa44/index.json"
      - run: npm i --prefix project Source/Presentation/Do-Svyazi.User.Web.ApiClient/Frontend/
      - run: npm ci --prefix project Source/Presentation/Do-Svyazi.User.Web.ApiClient/Frontend/
      - run: npm publish --access public --prefix project Source/Presentation/Do-Svyazi.User.Web.ApiClient/Frontend/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
